[package]
name = "rauta"
version = "0.1.0"
authors = ["nwin <nwin@users.noreply.github.com>"]

#[lib]
#name = "rauta"
#path = "src/main.rs"

[dependencies]
log = "0.3.0"
env_logger = "0.3.0"
rand = "0.3.0"
mio = "0.5.0"
postgres = "0.11.0"
num = "0.1.0"
bytes = "0.3.0"
libc = "0.2.0"